# Generated by Django 2.2.4 on 2019-08-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('provider_code', models.CharField(max_length=120)),
                ('provider', models.CharField(max_length=120)),
                ('provider_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('retailer_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('wholesaler_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
