# Generated by Django 2.2.4 on 2019-08-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='retailer_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesaler_price',
        ),
    ]
