# Generated by Django 2.2.4 on 2019-08-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190825_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='provider_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
